FROM benchflow/base-images:envconsul_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

#TODO: pin version of mysql-client
#TODO: if we will end up using the mc for now (minio is under heavy development), we should move it to a base-image for the collectors
RUN apk --update add wget gzip mysql-client && \
    wget -q --no-check-certificate -O /app/mc https://dl.minio.io/client/mc/release/linux-386/mc && \
    chmod +x /app/mc && \
    apk del --purge wget && \
    rm -rf /var/cache/apk/*

#TODO: remove, here for testing purposes
RUN /app/mc config host add http://195.176.181.55:9000 CYNQML6R7V12MTT32W6P SQ96V5pg02Z3kZ/0ViF9YY6GwWzZvoBmElpzEEjn

COPY ./bin/mysqldump_linux /app/mysqldump
RUN chmod +x /app/mysqldump
#TODO: change back, changed for testing purposes
#COPY ./services/300-dbms-mysql-mysqldump-collector.conf /apps/chaperone.d/300-dbms-mysql-mysqldump-collector.conf
CMD /app/mysqldump
#TODO: remove, here for testing purposes
RUN touch /app/test.tpl
#TODO: remove, here because of a problem killing the container
RUN rm /apps/chaperone.d/200-envconsul-envcp.conf
 
EXPOSE 8080
