FROM benchflow/base-images:minio-client_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

#TODO: pin version of mysql-client
RUN apk --update add gzip mysql-client && \
    rm -rf /var/cache/apk/*

COPY ./bin/mysqldump_linux /app/mysqldump
RUN chmod +x /app/mysqldump
#TODO: change back, changed for testing purposes
#COPY ./services/300-dbms-mysql-mysqldump-collector.conf /apps/chaperone.d/300-dbms-mysql-mysqldump-collector.conf
CMD /app/mysqldump

EXPOSE 8080
