FROM benchflow/base-images:envconsul_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

RUN apk --update add gzip && \
    rm -rf /var/cache/apk/*

COPY ./bin/logs_linux /app/logs
RUN chmod +x /app/logs
#COPY ./services/300-environment-logs-collector.conf /apps/chaperone.d/300-environment-logs-collector.conf
CMD /app/logs 
#TODO: remove, here for testing purposes
RUN touch /app/test.tpl
#TODO: remove, here because of a problem killing the container
RUN rm /apps/chaperone.d/200-envconsul-envcp.conf
 
EXPOSE 8080
