FROM benchflow/base-images:dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

#TODO: pin version of mysql-client
RUN apk --update add gzip mysql-client && \
    rm -rf /var/cache/apk/*

COPY ./bin/mysql_linux /app/mysql
RUN chmod +x /app/mysql
#TODO: change back, changed for testing purposes
#COPY ./services/300-dbms-mysql-collector.conf /apps/chaperone.d/300-dbms-mysql-collector.conf
CMD /app/mysql

EXPOSE 8080
