FROM benchflow/base-images:dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

RUN apk --update add gzip && \
    rm -rf /var/cache/apk/*

COPY ./bin/faban /app/faban
RUN chmod +x /app/faban
#COPY ./services/300-files-faban-collector.conf /apps/chaperone.d/300-files-faban-collector.conf
CMD /app/faban
 
EXPOSE 8080
