FROM benchflow/base-images:envconsul_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

RUN apk --update add gzip wget && \
	wget -q --no-check-certificate -O /app/mc https://dl.minio.io/client/mc/release/linux-386/mc && \
	chmod +x /app/mc && \
    rm -rf /var/cache/apk/*
    
#TODO: remove, here for testing purposes
RUN /app/mc config host add http://195.176.181.55:9000 CYNQML6R7V12MTT32W6P SQ96V5pg02Z3kZ/0ViF9YY6GwWzZvoBmElpzEEjn

COPY ./bin/stats_linux /app/stats
RUN chmod +x /app/stats
#COPY ./services/300-environment-stats-collector.conf /apps/chaperone.d/300-environment-stats-collector.conf
CMD /app/stats
#TODO: remove, here for testing purposes
RUN touch /app/test.tpl
#TODO: remove, here because of a problem killing the container
RUN rm /apps/chaperone.d/200-envconsul-envcp.conf 
 
EXPOSE 8080
