FROM benchflow/base-images:dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

RUN echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "http://dl-4.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN apk --update add gzip libpcap libstdc++ libgcc ncurses-terminfo-base ncurses-terminfo ncurses-libs nethogs@testing && \
    rm -rf /var/cache/apk/*

COPY ./bin/stats_linux /app/stats
RUN chmod +x /app/stats
#COPY ./services/300-environment-stats-collector.conf /apps/chaperone.d/300-environment-stats-collector.conf
CMD /app/stats
 
EXPOSE 8080
