FROM benchflow/base-images:minio-client_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

RUN apk --update add gzip && \
    rm -rf /var/cache/apk/*

COPY ./bin/stats_linux /app/stats
RUN chmod +x /app/stats
#COPY ./services/300-environment-stats-collector.conf /apps/chaperone.d/300-environment-stats-collector.conf
CMD /app/stats
 
EXPOSE 8080
